#!/usr/bin/env python3
"""Regenerate the self-updating parts of the logbook from per-week ``meta.yml`` files.

Single source of truth: each ``weeks/*/meta.yml``. This script reads them all and
regenerates:
  1. the README dashboard (progress bar + week table) and concept index, between the
     ``<!-- AUTO:START -->`` / ``<!-- AUTO:END -->`` markers, and
  2. ``shared/CHEATSHEET.md``, a compounding per-week + cross-week concept reference.

Run ``python tools/build_index.py`` to write, or ``--check`` to assert everything is
already in sync (used by CI so a stale README fails the build).
"""

from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
CHEATSHEET = ROOT / "shared" / "CHEATSHEET.md"
START = "<!-- AUTO:START -->"
END = "<!-- AUTO:END -->"

STATUS_LABEL = {
    "done": "✅ done",
    "in-progress": "🚧 in-progress",
    "todo": "⬜ todo",
}


def semester_total(n_weeks: int) -> int:
    """Planned weeks this semester (config `course.weeks_total`), else weeks present."""
    try:
        with (ROOT / "config.toml").open("rb") as fh:
            total = tomllib.load(fh).get("course", {}).get("weeks_total")
    except FileNotFoundError:
        total = None
    return max(int(total), n_weeks) if total else n_weeks


def load_weeks() -> list[dict]:
    weeks = []
    for meta_path in sorted(ROOT.glob("weeks/*/meta.yml")):
        data = yaml.safe_load(meta_path.read_text()) or {}
        data["_dir"] = meta_path.parent.name  # e.g. "week01"
        data.setdefault("datasets", [])
        data.setdefault("topics", [])
        data.setdefault("status", "todo")
        weeks.append(data)
    weeks.sort(key=lambda w: int(w["week"]))
    return weeks


def progress_bar(done: int, total: int, width: int = 24) -> str:
    total = max(total, 1)
    done = max(0, min(done, total))
    filled = round(width * done / total)
    bar = "█" * filled + "░" * (width - filled)
    pct = round(100 * done / total)
    return f"`{bar}`&nbsp;&nbsp;**{pct}%** &nbsp;·&nbsp; {done} of {total} weeks complete"


def render_dashboard(weeks: list[dict]) -> str:
    done = sum(1 for w in weeks if w["status"] == "done")
    total = semester_total(len(weeks))
    lines = ["### Progress", "", progress_bar(done, total), "", "### Weeks", ""]
    lines.append("| Week | Title | Datasets | Topics | Status | Notebook |")
    lines.append("|------|-------|----------|--------|--------|----------|")
    for w in weeks:
        wd = w["_dir"]
        datasets = ", ".join(f"`{d}`" for d in w["datasets"]) or "—"
        n_topics = f"{len(w['topics'])} topics" if w["topics"] else "—"
        status = STATUS_LABEL.get(w["status"], w["status"])
        nb = w.get("notebook", "")
        nb_cell = f"[`{nb}`](weeks/{wd}/{nb})" if nb else "—"
        lines.append(
            f"| {int(w['week']):02d} | {w.get('title', '')} | {datasets} | "
            f"{n_topics} | {status} | {nb_cell} |"
        )
    return "\n".join(lines)


def topic_to_weeks(weeks: list[dict]) -> dict[str, list[dict]]:
    index: dict[str, list[dict]] = {}
    for w in weeks:
        for topic in w["topics"]:
            index.setdefault(topic, []).append(w)
    return dict(sorted(index.items()))


def render_auto_block(weeks: list[dict]) -> str:
    # Auto-managed README section: Progress + Weeks only.
    # (The cross-week concept map still lives in shared/CHEATSHEET.md.)
    return render_dashboard(weeks)


def render_cheatsheet(weeks: list[dict]) -> str:
    lines = [
        "# Cumulative Cheat Sheet",
        "",
        "> Auto-generated by `tools/build_index.py` — do not edit by hand.",
        "> Grows as each week is tagged in its `meta.yml`.",
        "",
        "## By week",
        "",
    ]
    if not weeks:
        lines.append("_No weeks yet._")
    for w in weeks:
        wd = w["_dir"]
        nb = w.get("notebook", "")
        link = f"../weeks/{wd}/{nb}" if nb else f"../weeks/{wd}/"
        lines.append(f"### Week {int(w['week']):02d} — {w.get('title', '')}")
        lines.append("")
        lines.append(f"Notebook: [`{nb or wd}`]({link})")
        lines.append("")
        if w["topics"]:
            for topic in w["topics"]:
                lines.append(f"- `{topic}`")
        else:
            lines.append("- _no topics tagged yet_")
        lines.append("")

    lines.append("## All concepts (A→Z)")
    lines.append("")
    index = topic_to_weeks(weeks)
    if not index:
        lines.append("_No concepts tagged yet._")
    for topic, wks in index.items():
        refs = ", ".join(f"week{int(w['week']):02d}" for w in wks)
        lines.append(f"- `{topic}` — {refs}")
    return "\n".join(lines) + "\n"


def splice_readme(readme_text: str, auto_block: str) -> str:
    if START not in readme_text or END not in readme_text:
        raise SystemExit(
            f"README.md is missing the {START} / {END} markers; cannot inject the dashboard."
        )
    pre = readme_text.split(START)[0]
    post = readme_text.split(END)[1]
    return f"{pre}{START}\n\n{auto_block}\n\n{END}{post}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate logbook index + cheatsheet.")
    parser.add_argument("--check", action="store_true", help="fail if anything is out of sync")
    args = parser.parse_args()

    weeks = load_weeks()
    new_readme = splice_readme(README.read_text(), render_auto_block(weeks))
    new_cheatsheet = render_cheatsheet(weeks)

    if args.check:
        stale = []
        if README.read_text() != new_readme:
            stale.append("README.md")
        if not CHEATSHEET.exists() or CHEATSHEET.read_text() != new_cheatsheet:
            stale.append("shared/CHEATSHEET.md")
        if stale:
            print("Out of sync (run `make index`): " + ", ".join(stale))
            return 1
        print("Index is in sync.")
        return 0

    README.write_text(new_readme)
    CHEATSHEET.write_text(new_cheatsheet)
    print(f"Updated README.md and shared/CHEATSHEET.md from {len(weeks)} week(s).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
